"""재설계

Revision ID: 22f8d57ce7fb
Revises: a3a4e75119f0
Create Date: 2024-11-29 20:05:21.569442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22f8d57ce7fb'
down_revision: Union[str, None] = 'a3a4e75119f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('used_days', sa.Integer(), nullable=False),
    sa.Column('usage_rate', sa.Float(), nullable=False),
    sa.Column('cost_per_use', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_analysis_id'), 'usage_analysis', ['id'], unique=False)
    op.create_table('usage_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_used_days', sa.Integer(), nullable=False),
    sa.Column('daily_average', sa.Float(), nullable=True),
    sa.Column('weekly_average', sa.Float(), nullable=True),
    sa.Column('monthly_average', sa.Float(), nullable=True),
    sa.Column('last_used_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_patterns_id'), 'usage_patterns', ['id'], unique=False)
    op.drop_index('ix_monthly_summaries_id', table_name='monthly_summaries')
    op.drop_table('monthly_summaries')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_summaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('month', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('total_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('change_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('subscriptions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='monthly_summaries_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='monthly_summaries_pkey')
    )
    op.create_index('ix_monthly_summaries_id', 'monthly_summaries', ['id'], unique=False)
    op.drop_index(op.f('ix_usage_patterns_id'), table_name='usage_patterns')
    op.drop_table('usage_patterns')
    op.drop_index(op.f('ix_usage_analysis_id'), table_name='usage_analysis')
    op.drop_table('usage_analysis')
    # ### end Alembic commands ###
