"""요일데이터추가

Revision ID: 3ef950cba39c
Revises: 22f8d57ce7fb
Create Date: 2024-11-29 22:03:35.181536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef950cba39c'
down_revision: Union[str, None] = '22f8d57ce7fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('usage_analysis_contract_id_fkey', 'usage_analysis', type_='foreignkey')
    op.create_foreign_key(None, 'usage_analysis', 'contracts', ['contract_id'], ['id'])
    op.drop_constraint('usage_logs_contract_id_fkey', 'usage_logs', type_='foreignkey')
    op.create_foreign_key(None, 'usage_logs', 'contracts', ['contract_id'], ['id'])
    op.add_column('usage_patterns', sa.Column('most_used_weekday', sa.String(), nullable=True))
    op.drop_constraint('usage_patterns_contract_id_fkey', 'usage_patterns', type_='foreignkey')
    op.create_foreign_key(None, 'usage_patterns', 'contracts', ['contract_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usage_patterns', type_='foreignkey')
    op.create_foreign_key('usage_patterns_contract_id_fkey', 'usage_patterns', 'contracts', ['contract_id'], ['id'], ondelete='CASCADE')
    op.drop_column('usage_patterns', 'most_used_weekday')
    op.drop_constraint(None, 'usage_logs', type_='foreignkey')
    op.create_foreign_key('usage_logs_contract_id_fkey', 'usage_logs', 'contracts', ['contract_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'usage_analysis', type_='foreignkey')
    op.create_foreign_key('usage_analysis_contract_id_fkey', 'usage_analysis', 'contracts', ['contract_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
