"""월별관리디비추가

Revision ID: 478d2b613bac
Revises: ec3abd5656c5
Create Date: 2024-11-29 00:07:36.189893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '478d2b613bac'
down_revision: Union[str, None] = 'ec3abd5656c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_subscription_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('subscriptions', sa.JSON(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('previous_month_cost', sa.Float(), nullable=True),
    sa.Column('change_percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_subscription_summary_id'), 'monthly_subscription_summary', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monthly_subscription_summary_id'), table_name='monthly_subscription_summary')
    op.drop_table('monthly_subscription_summary')
    # ### end Alembic commands ###
