"""Add renewal_period field to contracts

Revision ID: 67b1ca474921
Revises: 92c31e446b24
Create Date: 2024-11-22 17:27:58.585588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67b1ca474921'
down_revision: Union[str, None] = '92c31e446b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('renewal_period', sa.Integer(), nullable=True))
    op.add_column('contracts', sa.Column('used_today', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'used_today')
    op.drop_column('contracts', 'renewal_period')
    # ### end Alembic commands ###
