"""월별디비관리추가

Revision ID: 6f77e8f739f5
Revises: ed3ef19f82e4
Create Date: 2024-11-29 18:19:03.277317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f77e8f739f5'
down_revision: Union[str, None] = 'ed3ef19f82e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('change_percentage', sa.Float(), nullable=True),
    sa.Column('subscriptions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_summaries_id'), 'monthly_summaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monthly_summaries_id'), table_name='monthly_summaries')
    op.drop_table('monthly_summaries')
    # ### end Alembic commands ###
