"""erase notification

Revision ID: 91c4c7c30237
Revises: 67b1ca474921
Create Date: 2024-11-27 18:40:51.882462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91c4c7c30237'
down_revision: Union[str, None] = '67b1ca474921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the notifications table and related indexes
    op.drop_index('ix_notifications_id', table_name='notifications')
    op.drop_table('notifications')

    # Update existing NULL values in 'used_today' to False before altering
    op.execute("UPDATE contracts SET used_today = FALSE WHERE used_today IS NULL")

    # Alter the 'used_today' column to be NOT NULL
    op.alter_column('contracts', 'used_today',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # Drop the 'is_notification_enabled' column
    op.drop_column('contracts', 'is_notification_enabled')

    # Drop the 'firebase_token' column from users
    op.drop_column('users', 'firebase_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Re-add the 'firebase_token' column to users
    op.add_column('users', sa.Column('firebase_token', sa.VARCHAR(), autoincrement=False, nullable=True))

    # Re-add the 'is_notification_enabled' column to contracts
    op.add_column('contracts', sa.Column('is_notification_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # Alter the 'used_today' column to allow NULL
    op.alter_column('contracts', 'used_today',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # Re-create the notifications table and related indexes
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notification_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name='notifications_contract_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_index('ix_notifications_id', 'notifications', ['id'], unique=False)
    # ### end Alembic commands ###