"""월별디비관리삭제

Revision ID: ed3ef19f82e4
Revises: 478d2b613bac
Create Date: 2024-11-29 17:47:03.232211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed3ef19f82e4'
down_revision: Union[str, None] = '478d2b613bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_monthly_subscription_summary_id', table_name='monthly_subscription_summary')
    op.drop_table('monthly_subscription_summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_subscription_summary',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('month', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('subscriptions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('total_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('previous_month_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('change_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='monthly_subscription_summary_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='monthly_subscription_summary_pkey')
    )
    op.create_index('ix_monthly_subscription_summary_id', 'monthly_subscription_summary', ['id'], unique=False)
    # ### end Alembic commands ###
